### PR TITLE
fixed issue caused by CanvasRenderingContext2D having properties on t…

### PR DESCRIPTION
**Pull request by rbmoore**
The following line was causing the error "TypeError: 'canvas' getter called on an object that does not implement interface CanvasRenderingContext2D."

https://github.com/platfora/Canteen/blob/master/src/canteen.js#L205

I was using FireFox, but a similar issue is seen in Chrome.

Information on what is causing the error can be found here: https://developers.google.com/web/updates/2015/04/DOM-attributes-now-on-the-prototype?hl=en

The change I made ensures that a property has a value in its descriptor before trying to access it.

### CODE REVIEW

**Comment by kevincolten** [comment]
+1 for merging this. Tested and works for me.

**Comment by rogierschouten** [comment]
:+1: +1 I have the same error

**Comment by ericdrowell** [comment]
@rbmoore thank you!

**Comment by rbmoore** [comment]
no problem, thanks for the merge!

**Pull request merged**
